services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: bc_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - redis
    networks:
      - devnet

  redis:
    image: redis:alpine
    container_name: bc_redis
    volumes:
      - redis_data:/data
    networks:
      - devnet

  web:
    image: nginx:alpine
    container_name: bc_web
    ports:
      - "8005:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - devnet

  vite:
    image: node:20-alpine
    container_name: bc_vite
    working_dir: /var/www/html
    ports:
      - "5176:5173"
    volumes:
      - ./src:/var/www/html
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    networks:
      - devnet

networks:
  devnet:
    driver: bridge

volumes:
  redis_data: